## The array system of numpy is not exactly like vector in lienar algebra!

### 1D array is not either a row vector or column vector, I regard it like a simplified row vector, but can't do the transpose.

In [ ]:
import numpy as np
vec = np.array([1, 3, 5])

print(vec.shape)

column_vec = np.array([[2],[4],[6]])
row_vec = np.array([[3, 5, 7]])
print(column_vec.shape, row_vec.shape)

(3,)
(3, 1) (1, 3)


### We can tell that 1D array is similar to 2D array(row vector) in many ways, but the biggest difference is that the transpose of 1D array is itself.

In [13]:
# Start with stacking with 1D array
vec_1D1 = np.array([1, 3, 5])
vec_1D2 = np.array([2, 4, 6])
x = np.hstack((vec_1D1 ,vec_1D2))
print("hstack: ", x.shape, x)

y = np.vstack((vec_1D1 ,vec_1D2))
print("vstack: ", y.shape,"\n", y)

print("Transpose of 1D array: ", vec_1D1.T.shape)

hstack:  (6,) [1 3 5 2 4 6]
vstack:  (2, 3) 
 [[1 3 5]
 [2 4 6]]
Transpose of 1D array:  (3,)


### Vstack and Hstack is so intuitively

In [5]:
row_vec = np.array([[3, 5, 7]])
row_vec1 = np.array([[3, 3, 3, 3]])

z = np.hstack((row_vec, row_vec))
print(z, z.shape)

v = np.vstack((row_vec, row_vec))
print(v, v.shape)

[[3 5 7 3 5 7]] (1, 6)
[[3 5 7]
 [3 5 7]] (2, 3)


### Column stack and row stack are meant for 1D array, and it's so convenient.

In [10]:
vec_1D1 = np.array([1, 3, 5])
vec_1D2 = np.array([2, 4, 6])

x = np.row_stack((vec_1D1, vec_1D2))
print(x, x.shape)

y = np.column_stack((vec_1D1, vec_1D2))
print(y, y.shape)

[[1 3 5]
 [2 4 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
